# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  api:
    build:
      context: "C:\\Dev\\LifeLikeManagment\\Printer"
      dockerfile: "./Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\szymo\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\szymo\\.nuget\\packages"
    image: "api:dev"
    ports: []
    volumes:
    - "C:\\Users\\szymo\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "C:\\Dev\\LifeLikeManagment\\Printer\\Api:/app:rw"
    - "C:\\Dev\\LifeLikeManagment\\Printer:/src:rw"
    working_dir: "/app"
